package com.example.ui

object LocalizedStrings {

    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.ARABIC) ArabicDict else EnglishDict
        return dict[key] ?: key
    }

    private val ArabicDict = mapOf(
        "app_title" to "المنشاوي للقرآن الكريم",
        "reciter_title" to "الشيخ محمد صديق المنشاوي",
        "home" to "الرئيسية",
        "surahs" to "السور",
        "downloads" to "التحميلات",
        "favorites" to "المفضلة",
        "settings" to "الإعدادات",
        "continue_listening" to "متابعة الاستماع",
        "resume_surah" to "استئناف سورة ",
        "recently_played" to "المستمع إليه مؤخراً",
        "most_played" to "الأكثر استماعاً",
        "favorite_surahs" to "السور المفضلة",
        "downloaded_surahs" to "السور المحملة",
        "search_hint" to "ابحث برقم أو اسم السورة...",
        "play" to "تشغيل",
        "download" to "تحميل",
        "delete" to "حذف",
        "share" to "مشاركة",
        "revelation_meccan" to "مكية",
        "revelation_medinan" to "مدنية",
        "verses" to "آية",
        "minutes" to "دقيقة",
        "language_option" to "اللغة",
        "theme_option" to "المظهر",
        "theme_system" to "تلقائي (حسب النظام)",
        "theme_light" to "فاتح",
        "theme_dark" to "داكن",
        "audio_provider" to "مصدر الصوت والبث",
        "playback_speed" to "سرعة القراءة والتشغيل",
        "sleep_timer" to "مؤقت النوم الإغلاقي",
        "sleep_timer_inactive" to "غير مفعل",
        "sleep_timer_val" to "دقيقة",
        "cache_management" to "إدارة الذاكرة المؤقتة",
        "clear_cache" to "مسح كل التحمليات والملفات",
        "cache_cleared" to "تم مسح ذاكرة التخزين المؤقتة بنجاح",
        "share_message" to "استمع إلى سورة %s بصوت الشيخ المنشاوي بجودة عالية عبر تطبيق المنشاوي قرآن.",
        "empty_downloads" to "لا توجد سور محملة حالياً. يمكنك تفعيل الملفات دون اتصال بتحميلها من قائمة السور.",
        "empty_favorites" to "قائمتك المفضلة فارغة. اضغط على أيقونة القلب على أي سورة لحفظها للوصول السريع.",
        "empty_recent" to "لم تستمع لأي سورة من قبل. ابدأ الاستماع الآن لترطيب يومك بالقرآن الكريم.",
        "download_done" to "تم التحميل بنجاح",
        "downloading" to "جاري التحميل... ",
        "reciter_desc" to "صوت خاشع باكي يلامس القلوب، من أعظم مدارس التلاوة في العالم الإسلامي."
    )

    private val EnglishDict = mapOf(
        "app_title" to "Al-Minshawi Quran",
        "reciter_title" to "Sheikh Al-Minshawi",
        "home" to "Home",
        "surahs" to "Library",
        "downloads" to "Downloads",
        "favorites" to "Favorites",
        "settings" to "Settings",
        "continue_listening" to "Continue Listening",
        "resume_surah" to "Resume Surah ",
        "recently_played" to "Recently Played",
        "most_played" to "Most Played",
        "favorite_surahs" to "Favorites",
        "downloaded_surahs" to "Offline Downloads",
        "search_hint" to "Search by number or name...",
        "play" to "Play",
        "download" to "Download",
        "delete" to "Delete",
        "share" to "Share",
        "revelation_meccan" to "Meccan",
        "revelation_medinan" to "Medinan",
        "verses" to "Verses",
        "minutes" to "min",
        "language_option" to "Language",
        "theme_option" to "Theme",
        "theme_system" to "System Default",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "audio_provider" to "Audio Provider Service",
        "playback_speed" to "Playback Speed",
        "sleep_timer" to "Sleep Close Timer",
        "sleep_timer_inactive" to "Off",
        "sleep_timer_val" to "minutes",
        "cache_management" to "Local Storage Management",
        "clear_cache" to "Delete All Downloaded Surahs",
        "cache_cleared" to "All downloads cleared successfully",
        "share_message" to "Listen to Surah %s recited beautifully by Sheikh Al-Minshawi via Al-Minshawi Quran App.",
        "empty_downloads" to "No offline surahs yet. Go to library and click the download icon to cache surahs for offline listening.",
        "empty_favorites" to "Your favorites list is empty. Heart any surah to pin it here.",
        "empty_recent" to "No recitations played recently. Open the Library to start exploring.",
        "download_done" to "Downloaded",
        "downloading" to "Downloading... ",
        "reciter_desc" to "A deeply spiritual, resonant voice from Egypt's golden era of Quran recitations."
    )
}
